### ISSUE TITLE
Post Installation Instructions

### ISSUE THREAD

**Issue by arjun921** [sig-ml/crossval#1]
I managed to install it on my Mac..
I Think. :|

Here's the terminal output - 

```
sudo ./setup.sh 
./setup.sh: line 6: ./env/bin/activate: No such file or directory
./setup.sh: line 9: virtualenv: command not found
./setup.sh: line 10: env/bin/activate: No such file or directory
The directory '/Users/arjuns/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/arjuns/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting Django==1.10 (from -r requirements.txt (line 1))
  Downloading Django-1.10-py2.py3-none-any.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 46kB/s 
Requirement already satisfied (use --upgrade to upgrade): numpy==1.11.1 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pandas==0.18.1 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil==2.5.3 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Collecting pytz==2016.6.1 (from -r requirements.txt (line 5))
  Downloading pytz-2016.6.1-py2.py3-none-any.whl (481kB)
    100% |████████████████████████████████| 481kB 67kB/s 
Requirement already satisfied (use --upgrade to upgrade): scikit-learn==0.17.1 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Collecting scipy==0.18.0 (from -r requirements.txt (line 7))
  Downloading scipy-0.18.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (21.9MB)
    100% |████████████████████████████████| 21.9MB 20kB/s 
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Collecting sklearn==0.0 (from -r requirements.txt (line 9))
  Downloading sklearn-0.0.tar.gz
Installing collected packages: Django, pytz, scipy, sklearn
  Found existing installation: pytz 2016.4
    DEPRECATION: Uninstalling a distutils installed project (pytz) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling pytz-2016.4:
      Successfully uninstalled pytz-2016.4
  Found existing installation: scipy 0.17.1
    DEPRECATION: Uninstalling a distutils installed project (scipy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling scipy-0.17.1:
      Successfully uninstalled scipy-0.17.1
  Running setup.py install for sklearn ... done
Successfully installed Django-1.10 pytz-2016.6.1 scipy-0.18.0 sklearn-0.0
/Users/arjuns/Working DIrectory/IIITM-K/crossval
 Webserver Setup started.
rm: db.sqlite3: No such file or directory
Migrations for 'contest':
  contest/migrations/0006_auto_20160903_1509.py:
    - Alter field max_submissions_per_day on contest
    - Alter field reverse_lb on contest
    - Alter field tos on contest
    - Alter field code_file on submission
    - Alter field comment on submission
    - Alter field test_file on submission
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, contest, sessions
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying contest.0001_initial... OK
  Applying contest.0002_contest_check_script... OK
  Applying contest.0003_auto_20160825_1209... OK
  Applying contest.0004_contest_metric... OK
  Applying contest.0005_contest_reverse_lb... OK
  Applying contest.0006_auto_20160903_1509... OK
  Applying sessions.0001_initial... OK
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 193, in handle
    collected = self.collect()
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 115, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 112, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/staticfiles/utils.py", line 28, in get_files
    directories, files = storage.listdir(location)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/core/files/storage.py", line 399, in listdir
    for entry in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/Users/arjuns/Working DIrectory/IIITM-K/crossval/crossval/staticfiles'
 Set up a superuser. 
Username (leave blank to use 'root'): 
Email address: arjun.mi1@iiitmk.ac.in
Password: 
Password (again): 
Superuser created successfully.
```

Now in the beginning it says clearly that it cant find the virtual environment. 
So, did it work or not?

If it did, what is the link I need to open on my browser to view the admin page?

**Comment by arjun921** [comment]
P.S. http://localhost:8000/ didnt work (figured out the port number from your screenshots)

**Comment by theSage21** [comment]
It appears that everything worked except for the `static files` command. That should be ok though. I've added a new `serve.sh` script which should get your basic development server running.  

Do a `$ git pull origin master`, then `$ ./setup.sh` followed by `serve.sh`.

You should be able to use the http://localhost:8000/contest/ link to view the website.

**Comment by arjun921** [comment]
Working now 👍 :)
