### ISSUE TITLE
Login Not working

### ISSUE THREAD

**Issue by arjun921** [sig-ml/crossval#2]
# Error Trying to login

I'm not able to login after the setup worked
-the setup.sh showed error for virtualenv not found again
-Not entirely sure if it worked completely or not. 
-At least this time it showed up the webpages though 

Here's the error I found while trying to log in.
Python 2 and 3 installed, but does it run python using the command python? or does it use python3 to execute?

I'm attaching the screenshot which states that the database is read only(comes when I'm trying to log in)
## Terminal output from setup.sh:

```
Arjuns-MBP:crossval arjuns$ sudo ./setup.sh 
Password:
./setup.sh: line 6: ./env/bin/activate: No such file or directory
 Virtualenv Not Found. Creating new env. 
./setup.sh: line 10: virtualenv: command not found
./setup.sh: line 11: env/bin/activate: No such file or directory
 Installing requirements. 
The directory '/Users/arjuns/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/arjuns/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): Django==1.10 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): numpy==1.11.1 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pandas==0.18.1 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil==2.5.3 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): pytz==2016.6.1 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): scikit-learn==0.17.1 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): scipy==0.18.0 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): sklearn==0.0 in /Users/arjuns/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 9))
 Setup folder path is:  /Users/arjuns/Working DIrectory/IIITM-K/crossval
 Webserver Setup started.
 Removing old Database if any.
 Creating new database structures.
No changes detected
 Creating new database.
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, contest, sessions
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying contest.0001_initial... OK
  Applying contest.0002_contest_check_script... OK
  Applying contest.0003_auto_20160825_1209... OK
  Applying contest.0004_contest_metric... OK
  Applying contest.0005_contest_reverse_lb... OK
  Applying contest.0006_auto_20160903_1509... OK
  Applying sessions.0001_initial... OK
 Collecting static files.
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 193, in handle
    collected = self.collect()
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 115, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 112, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/staticfiles/utils.py", line 28, in get_files
    directories, files = storage.listdir(location)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/core/files/storage.py", line 399, in listdir
    for entry in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/Users/arjuns/Working DIrectory/IIITM-K/crossval/crossval/staticfiles'
 Set up a superuser. 
Username (leave blank to use 'root'): 
Email address: arjun.mi1@iiitmk.ac.in
Password: 
Password (again): 
Superuser created successfully.
 Setup is done. 
```
## Terminal output from serve.sh:

```
Arjuns-MBP:crossval arjuns$ ./serve.sh 
./serve.sh: line 6: ./env/bin/activate: No such file or directory
 Virtualenv Not Found.  Please run setup.sh or report this on github
Performing system checks...

System check identified no issues (0 silenced).
September 03, 2016 - 15:43:40
Django version 1.10, using settings 'crossval.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Not Found: /
[03/Sep/2016 15:43:58] "GET / HTTP/1.1" 404 2260
Not Found: /favicon.ico
[03/Sep/2016 15:43:59] "GET /favicon.ico HTTP/1.1" 404 2293
[03/Sep/2016 15:44:10] "GET /contest HTTP/1.1" 301 0
[03/Sep/2016 15:44:10] "GET /contest/ HTTP/1.1" 200 1624
[03/Sep/2016 15:49:42] "GET /admin HTTP/1.1" 301 0
[03/Sep/2016 15:49:42] "GET /admin/ HTTP/1.1" 302 0
[03/Sep/2016 15:49:42] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1653
[03/Sep/2016 15:49:42] "GET /static/admin/css/login.css HTTP/1.1" 200 1203
[03/Sep/2016 15:49:42] "GET /static/admin/css/base.css HTTP/1.1" 200 15937
[03/Sep/2016 15:49:42] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[03/Sep/2016 15:49:43] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
[03/Sep/2016 15:49:43] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
[03/Sep/2016 16:02:58] "GET /contest/ HTTP/1.1" 200 1624
[03/Sep/2016 16:15:26] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1653
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 377, in login
    return login(request, **defaults)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/auth/views.py", line 47, in inner
    return func(*args, **kwargs)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/auth/views.py", line 82, in login
    auth_login(request, form.get_user())
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 109, in login
    request.session.cycle_key()
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 311, in cycle_key
    self.create()
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 54, in create
    self.save(must_create=True)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 87, in save
    obj.save(force_insert=must_create, force_update=not must_create, using=using)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/db/models/query.py", line 1043, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/arjuns/anaconda/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: attempt to write a readonly database
[03/Sep/2016 16:15:32] "POST /admin/login/?next=/admin/ HTTP/1.1" 500 168514
```
## Screenshot

![image](https://cloud.githubusercontent.com/assets/10341039/18226144/e5f78b44-7220-11e6-9097-4819472e9fcf.png)

**Comment by theSage21** [comment]
1. Some better [markdown](https://daringfireball.net/projects/markdown/basics) might be good for future issues.
2. I think the `virtualenv` is not getting activated. Tweak the script to match your operating system's needs.

**Comment by arjun921** [comment]
Still getting a hang of markdown :| Sorry, I'll keep that in mind.

I'll make a commit after fixing it for Mac os in a new file.

**Comment by theSage21** [comment]
Sure. As and when you please. :smile:

**Comment by theSage21** [comment]
Working yet?

**Comment by arjun921** [comment]
Wasn’t free to work on it again.
Will check and update soon.

**Comment by arjun921** [comment]
I just retried it from scratch after `git pull origin master` and it worked :|
